// =============================================================================
// Auto-generated SVG Image Themes
// Generated by scripts/generate_pieces.ts
// =============================================================================
import type { KifuTheme } from '../types';
import { richTheme, textTheme } from './baseThemes';

import wood_FU from '../assets/pieces/wood/FU.svg';
import dark_FU from '../assets/pieces/dark/FU.svg';
import glass_FU from '../assets/pieces/glass/FU.svg';
import wood_KY from '../assets/pieces/wood/KY.svg';
import dark_KY from '../assets/pieces/dark/KY.svg';
import glass_KY from '../assets/pieces/glass/KY.svg';
import wood_KE from '../assets/pieces/wood/KE.svg';
import dark_KE from '../assets/pieces/dark/KE.svg';
import glass_KE from '../assets/pieces/glass/KE.svg';
import wood_GI from '../assets/pieces/wood/GI.svg';
import dark_GI from '../assets/pieces/dark/GI.svg';
import glass_GI from '../assets/pieces/glass/GI.svg';
import wood_KI from '../assets/pieces/wood/KI.svg';
import dark_KI from '../assets/pieces/dark/KI.svg';
import glass_KI from '../assets/pieces/glass/KI.svg';
import wood_KA from '../assets/pieces/wood/KA.svg';
import dark_KA from '../assets/pieces/dark/KA.svg';
import glass_KA from '../assets/pieces/glass/KA.svg';
import wood_HI from '../assets/pieces/wood/HI.svg';
import dark_HI from '../assets/pieces/dark/HI.svg';
import glass_HI from '../assets/pieces/glass/HI.svg';
import wood_OU from '../assets/pieces/wood/OU.svg';
import dark_OU from '../assets/pieces/dark/OU.svg';
import glass_OU from '../assets/pieces/glass/OU.svg';
import wood_TO from '../assets/pieces/wood/TO.svg';
import dark_TO from '../assets/pieces/dark/TO.svg';
import glass_TO from '../assets/pieces/glass/TO.svg';
import wood_NY from '../assets/pieces/wood/NY.svg';
import dark_NY from '../assets/pieces/dark/NY.svg';
import glass_NY from '../assets/pieces/glass/NY.svg';
import wood_NK from '../assets/pieces/wood/NK.svg';
import dark_NK from '../assets/pieces/dark/NK.svg';
import glass_NK from '../assets/pieces/glass/NK.svg';
import wood_NG from '../assets/pieces/wood/NG.svg';
import dark_NG from '../assets/pieces/dark/NG.svg';
import glass_NG from '../assets/pieces/glass/NG.svg';
import wood_UM from '../assets/pieces/wood/UM.svg';
import dark_UM from '../assets/pieces/dark/UM.svg';
import glass_UM from '../assets/pieces/glass/UM.svg';
import wood_RY from '../assets/pieces/wood/RY.svg';
import dark_RY from '../assets/pieces/dark/RY.svg';
import glass_RY from '../assets/pieces/glass/RY.svg';

// ---------------------------------------------------------------------------
// Theme Images
// ---------------------------------------------------------------------------

const woodImages: Record<string, string> = {
  FU: wood_FU,
  KY: wood_KY,
  KE: wood_KE,
  GI: wood_GI,
  KI: wood_KI,
  KA: wood_KA,
  HI: wood_HI,
  OU: wood_OU,
  TO: wood_TO,
  NY: wood_NY,
  NK: wood_NK,
  NG: wood_NG,
  UM: wood_UM,
  RY: wood_RY,
};

const darkImages: Record<string, string> = {
  FU: dark_FU,
  KY: dark_KY,
  KE: dark_KE,
  GI: dark_GI,
  KI: dark_KI,
  KA: dark_KA,
  HI: dark_HI,
  OU: dark_OU,
  TO: dark_TO,
  NY: dark_NY,
  NK: dark_NK,
  NG: dark_NG,
  UM: dark_UM,
  RY: dark_RY,
};

const glassImages: Record<string, string> = {
  FU: glass_FU,
  KY: glass_KY,
  KE: glass_KE,
  GI: glass_GI,
  KI: glass_KI,
  KA: glass_KA,
  HI: glass_HI,
  OU: glass_OU,
  TO: glass_TO,
  NY: glass_NY,
  NK: glass_NK,
  NG: glass_NG,
  UM: glass_UM,
  RY: glass_RY,
};

// ---------------------------------------------------------------------------
// Themes
// ---------------------------------------------------------------------------

/** Wood Theme: 木目調のグラデーション画像駒 */
export const imageWoodTheme: KifuTheme = {
  ...richTheme,
  name: 'imageWood',
  piece: {
    ...richTheme.piece,
    mode: 'image',
    senteImages: woodImages,
  },
};

/** Dark Theme: 黒基調のスタイリッシュな駒とダーク盤面 */
export const imageDarkTheme: KifuTheme = {
  ...textTheme,
  name: 'imageDark',
  board: {
    ...textTheme.board,
    background: '#121212',
    gridColor: '#444444',
    starPointColor: '#444444',
    highlightColor: 'rgba(255, 255, 255, 0.1)',
    borderColor: '#333333',
    labelColor: '#666666',
  },
  hand: {
    ...textTheme.hand,
    background: '#1e1e1e',
    textColor: '#e0e0e0',
    borderColor: '#333333',
  },
  piece: {
    ...textTheme.piece,
    mode: 'image',
    senteImages: darkImages,
  },
};

/** Glass Theme: 半透明・グラスモーフィズム調 */
export const imageGlassTheme: KifuTheme = {
  ...richTheme,
  name: 'imageGlass',
  board: {
    ...richTheme.board,
    background: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)',
    gridColor: 'rgba(0,0,0,0.2)',
    starPointColor: 'rgba(0,0,0,0.2)',
    highlightColor: 'rgba(255, 255, 255, 0.4)',
    borderColor: 'rgba(255,255,255,0.5)',
    labelColor: 'rgba(0,0,0,0.4)',
  },
  hand: {
    ...richTheme.hand,
    background: '#cceceb', // Soft glass-like cyan to make white pieces visible on any background
    textColor: '#333',
    borderColor: 'rgba(0,0,0,0.1)',
  },
  piece: {
    ...richTheme.piece,
    mode: 'image',
    senteImages: glassImages,
  },
};
